### PR TITLE
optimize svg and perf improvements

### LINKED ISSUE #32: Rich svg files not being optimized
Svgs that have comments or unknown tags, we should optimize them

### PR DESCRIPTION
**Pull request by eloytoro**
Closes #32

### CODE REVIEW

**Comment by jhamlet** [comment]
@eloytoro First, I want to say thanks for contributing. I really appreciate it.

Secondly, there is already a `svgo-loader` that can be used to optimize before `svg-react-loader` gets a hold of the SVG/XML. I use a `preloader` in my **webpack configuration** to handle poorly formed SVGs. I've tried to follow the *webpack loader* convention of [do only a single task](https://webpack.github.io/docs/how-to-write-a-loader.html#do-only-a-single-task).

So, I'm afraid this pull-request is not required. Keeping any optimizations as a separate loader allows you configure that how you want, and `svgs-react-loader` does not have to handle additional configuration options to pass to `svgs-loader`.

I hope you understand,

;-j

**Comment by eloytoro** [comment]
@jhamlet ok, I did try using `svgo-loader` but had some problems with it, will try again.
Please take a look at the perf improvements.
Right now the code is reading the `template.txt` everytime a source is passed to the loader.
It also constructs a `xml2js` parser for every source, I took care of that.
Maybe I create a separate PR for this? (only if the greenlight is given)

**Comment by jhamlet** [comment]
@eloytoro Thanks for pointing those out.

Unfortunately, your timing is a week too late. I am getting ready to make [v0.4.0](https://github.com/jhamlet/svg-react-loader/tree/version-0.4.0) the latest. Its a complete refactor, and I've taken care of many of this things and made it more pluggable.

You can try it out by `npm i svg-react-loader@next`

If you want to do a separate pull-request with just the perf fixes, I'll see to getting that in a patch revision (v0.3.8 i think).

;-j

**Comment by jhamlet** [comment]
@eloytoro Just one note: I came across information that the `xml2js.Parser` can get in a weird state if used over and over again. So, I explicitly create a new one, both in this code, and in the next version.

Since, this code-base does not have very good tests, I'd rather not include that adjustment here.

The reading of the template file on every pass is completely valid though (face-palming), **but do not** use `readFileSync` use the asynchronous version and store the value. If the template variable is already defined, then just call the callback immediately with the already read template.

Thanks,

;-j

**Pull request closed without merging**
