### PR TITLE
Fix react deprecation warnings

### PR DESCRIPTION
**Pull request by konstantin24121**
Add create-react-class into dependencies
and change in template

Issue: #66

### CODE REVIEW

**Comment by Andarist** [comment]
next step would also be to migrate this to es6 classes, right?

**Comment by konstantin24121** [comment]
I'm not sure that is big difference there, but it can extend from PureComponent. @Andarist what did you think?

**Comment by Andarist** [comment]
There are 2 differences - one u have mentioned (but aint sure if we should incorporate, it would break actual semantics now) and second which is - es6 classes are the preferred way for creating class components now and dont need extra dependency of create-react-class - most ppl use babel anyway.

create-react-class was kept only so the migration path is easier and even deprecation warning has mentioned this

**Comment by konstantin24121** [comment]
I agree with you, but this question must be resolved with maintainer

**Comment by tomasztomys** [comment]
Please release new version of loader.

**Comment by jessy1092** [comment]
+1

@jhamlet I use this PR on my own project. It works perfectly. It would be useful if official release include this feature.

**Comment by srosset81** [comment]
Any news on this ? The React deprecation warning are really annoying...

**Pull request closed without merging**
